name = "PyPlot2Igor"
uuid = "4aea8070-c6ca-4677-ac9e-cb9fcba1134a"
authors = ["MLackner <lacknersmichael@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
ProgressMeter = "1"
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
